### ISSUE TITLE
Sezione Revocation Endpoint

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#101]
Non è molto chiara. Ad esempio si dice "The OP will have to revoke the token specified in the request and will have to end the Single Sign-On session, if it is still active" ma da nessuna parte si parla di sessione di SSO… 
Inoltre io fare una sezione più generale sui meccanismi di logout nella quale fare riferimento a questa sezione.

**Comment by peppelinux** [comment]
Will have -> MUST

**Comment by peppelinux** [comment]
si, il termine SSO è misleading.

**Comment by fmarino-ipzs** [comment]
Risolta con la PR #144
