### ISSUE TITLE
Sezione Attribute Authority Metadata

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#102]
- rimuovere il riferimento al metadata da trust_mark_issuer che mi pare di capire verrà rimosso anche dallo standard.
- il metadata da oauth_authorization_server è obbligatorio solo per i flussi protected e private. 

In generale farei una valutazione generale se rimuovere proprio la parte AA e pensare di predisporre un analogo documento su docs italia sulle AA (io sare più favorevole a questa opzione)

**Comment by peppelinux** [comment]
AA solo per oidc si intende?

Vediamo come sintetizzare i contenuti per capire se riusciamo ad includerli nel repo attuale
