### ISSUE TITLE
Sezione Differenze con OIDC Federation

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#103]
A mio avviso l'unica differenza è sull'endpoint di listing dove noi prevediamo un parametro di input (eventualmente anche l'id TM #96 ) 
Il resto secondo me non è una differenza perché rappresenta solo un profilo specifico dello standard.

**Comment by peppelinux** [comment]
entity_type è ormai standard, va solo rimosso dalla lista delle differenze
