### ISSUE TITLE
Sezione algoritmi supportati

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#105]
- Spostare la sezione degli algoritmi supportati dopo la sezione Revocation endpoint e rinominarla in Algoritmi Crittografici
- Aggiungere una nota su algo di firma per federation

**Comment by peppelinux** [comment]
Credo che gli algoritmi vadano nella sezione dei metadata o prima di a questa perché nei parametri dei metadata viene citata

**Comment by fmarino-ipzs** [comment]
Gli algoritmi di firma vengono già introdotti nella sezione di firma dell'EC. L'idea di spostarli alla fine è solo per facilitare la lettura e rendere la sezione sugli algoritmi una sezione separata dalla parte dei metadata OIDC. Nella lettura su docs italia abbiamo sempre i link. @peppelinux , che ne pensi?
