### ISSUE TITLE
Metadata da federation_entity

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#116]
- Togliere organization_name dal metadata RP e metterlo nel metadata da federation_entity
- Aggiungere homepage_uri
- Policy_uri 
- Sarebbe meglio poter avere anche logo_uri nel metadata da federation_entity e non nel metadata RP OP.

L'idea di base è quella di mettere nel metadata da RP/OP solo i dati tecnici di protocollo e tutti i dati "non strettamente necessari" (che riguardano ad esempio gli aspetti di onboarding) nel metadata di federation_entity.

Ho appena aperto una issue anche su bitbucket dove propongo organization_name come obbligatorio e logo_uri come opzionale
https://bitbucket.org/openid/connect/issues/1712/federation_entity-metadata

**Comment by peppelinux** [comment]
Nessun problema anche a lasciarle in rp e op, ok per me

**Comment by fmarino-ipzs** [comment]
ok, io eviterei di avere duplicazione di informazioni. Vado a fare PR asap.
