### ISSUE TITLE
Sessione lunga rinnovabile

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#129]
Nella sezione token endpoint si fa riferimento alla sessione lunga rinnovabile (https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n41-integrazione_ll.gg_._openid_connect_in_spid.pdf#page=6)

A mio avviso questa funzionalità andrebbe inquadrata nel contesto del Single SignOn e non ha nulla a che vedere con l'utilizzo del Refresh token che da standard abilita l'utilizzo di scenari ti tipo offline_access per ottenere i dati dell'utente e non una autenticazione in regime di SSO.

Le mie proposte sono:

1. Eliminiamo ogni riferimento alle sessioni lunghe rinnovabili
2. Facciamo un box di disambiguazione dove riporteremo che questo meccanismo è previsto solo per SPID e non per CIE.

@agcolella @nunzionapoli @damikael @peppelinux che ne pensate?

**Comment by peppelinux** [comment]
Per me sono ok entrambe le soluzioni editoriali, chiedo ai colleghi della AgID di esprimere la loro preferenza

@damikael @AntonioFlorio^

**Comment by damikael** [comment]
La proposta 1. implica modifica sostanziale alle LL.GG.
Credo convenga la proposta 2.

**Comment by fmarino-ipzs** [comment]
Risolta con la PR #144
