### ISSUE TITLE
Metadata di Federazione - aggiungere federation_resolve_endpoint per tutte le entità

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#14]
![image](https://user-images.githubusercontent.com/1297620/174898030-b7ca24a7-bf54-4fae-8dd1-20eca1ace574.png)

**Comment by sp640919** [comment]
Non ho capito. Devo modificare metadata_oidc.rst e aggiungere il paragrafo "Metadata di Soggetto Aggregatore" alla riga 213?

**Comment by peppelinux** [comment]
noi diciamo che resolve endpoint deve essere esposto da tutte le entità, pertanto nella tabella dei claim dei metadata dobbiamo indicare questo endpoint o definirlo in maniera chiara.

Se questa informazione ti manca significa che il testo va migliorato, perché non si evince dalla documentazione che ti abbiamo fornito. È importante che su docs italia sia intelleggibile

**Comment by sp640919** [comment]
federation_resolve_endpoint deve stare anche in metadata_oidc_rp e op, non solo fa

**Comment by peppelinux** [comment]
Qui devo revisionare perché federation_resolve_endpoint no nsta nel metadata di RP e OP ma nel metadata di federation_entity presente nel EC di RP e OP
