### ISSUE TITLE
id_code as json or string

### ISSUE THREAD

**Issue by damikael** [italia/spid-cie-oidc-docs#146]
id_code è qui 
https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/en/trust_marks.rst#trust-mark-composition

definito come json, composto da diversi elementi

tuttavia, qui
https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/en/soggetti_aggregatori.rst#intermediate-entities

è utilizzato per la composizione del client_id.

**Comment by fmarino-ipzs** [comment]
L'id_code nel trust mark contiene gli identificativi univoci dell'Ente che, ad esempio nel caso della PA, possono essere più di uno (IPA, codice AOO, codice UO). 
Per la costruzione del web path nel caso di SA full, se siete d'accordo, potremmo indicare di inserire uno dei codici identificativi e nel caso di PA potremmo dire che DOVREBBERO inserire il codice identificativo più specifico. Ad esempio se un Ente ha codice IPA, AOO e UO, il SA DOVREBBE inserire nel web path il codice UO. Che ne pensate? Avete altre idee?
