### ISSUE TITLE
typo in claim "address" definition

### ISSUE THREAD

**Issue by nunzionapoli** [italia/spid-cie-oidc-docs#156]
La descrizione del claim dovrebbe essere la seguente:

JSON Object (address): 
Json contenente le proprietà che rappresentano:

- "**street_address**":L'attributo contiene la tipologia (via, viale, piazza …), l'indirizzo e il numero civico. Le tre informazioni sono preferibilmente ordinate come d'uso per lo specifico Stato.
- "**postal_code**": CAP
-  "**locality**":Comune
-  "**region**": Provincia
-  "**country_code**" : Nazione

**Comment by peppelinux** [comment]
@nunzionapoli fatto nella seguente PR, se ho capito bene il problema, pertanto ti chiedo una revisione per conferma

https://github.com/italia/spid-cie-oidc-docs/pull/157
