### ISSUE TITLE
Integrare direttamente nelle sezioni dei metadata senza fare diff editoriali

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#16]
![image](https://user-images.githubusercontent.com/1297620/174898342-8ed3480c-1617-49a5-9a1b-c07dfdcbf8c1.png)

**Comment by sp640919** [comment]
Devo portare queste sezioni dentro "metadata_oidc.rst"?

**Comment by peppelinux** [comment]
nella sezione relativa alle federation_entity (TA e intermediaries)

**Comment by peppelinux** [comment]
integrare nei field dei metadata delle FA
