### ISSUE TITLE
Parametro acr nell'ID Token

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#167]
Nella tabella ([qui](https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/token_endpoint.html#id-token)) si riporta:

<html>
<body>

acr | Livello di autenticazione effettivo. PUÒ essere uguale o superiore a quello richiesto dal RP nella Authentication Request.
-- | --

</body>
</html>

Probabilmente sarebbe più corretto modificare PUÒ in DEVE.

**Comment by peppelinux** [comment]
si, dovremmo specificare che DEVE essere uguale o superiore

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/spid-cie-oidc-docs/pull/183/commits/2ae8864d1281f1198724a521f6edccc6bb1ee245
