### ISSUE TITLE
Test metadata OIDC 1.2.4 Unclear error message

### ISSUE THREAD

**Issue by luckeez** [italia/spid-cie-oidc-docs#174]
In SPID RP Metadata Validator ( https://validator-test.spid.gov.it/oidc/rp/ ) I get an Error Message not clear in 1.2.4 Test.

>Description
>The signature of the JWS document MUST be valid
>Error Message
>The "url" argument must be of type string. Received undefined

It is not clear where should the URL argument appear. Is it a general claim (which I can't find), or is it referring to `private_key_jwt` ([ref](https://openid.net/specs/openid-connect-federation-1_0.html#section-4.3-4.6.3.2)) Authentication method?

**Comment by peppelinux** [comment]
I think that this issue is related to the validation-test suite since we don't have any reference of that in the documentation

@damikael ^

**Comment by damikael** [comment]
Please move the issue to the repo 
https://github.com/AgID/spid-oidc-check-rp

Thanks
