### ISSUE TITLE
Typo in Sezione Token Endpoint - Request 

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#176]
Il parametro client_assertion_type deve essere valorizzato in urn:ietf:params:oauth:client-assertion-type:jwt-bearer come da [RFC7523, Section 2.2](https://www.rfc-editor.org/rfc/rfc7523#section-2.2)

Sistemare anche gli esempi non normativi relativi

**Comment by peppelinux** [comment]
Così lo leggo qui
https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/en/token_endpoint.rst
https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/it/token_endpoint.rst

dove manca?
