### ISSUE TITLE
Fix Sezione Userinfo endpoint - Response

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#177]
- Aggiungere tabella JOSE Header parameters
- Nel payload del JWT aggiungere i parametri iat e exp

**Comment by peppelinux** [comment]
li vedo nell'esempio

https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/en/userinfo_endpoint.rst#response
https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/it/userinfo_endpoint.rst#response

e li ho aggiunti nella tabella qui
f8484759193d38c1e7ba6d13820a8aa04c682bbb
