### ISSUE TITLE
URGENTE: tag versione_corrente

### ISSUE THREAD

**Issue by nicola-milani** [italia/spid-cie-oidc-docs#190]
Buongiorno, 
abbiamo necessità che venga pubblicata la versione_corrente della documentazione perché la tabella attributi attualmente pubblicata non è conforme con l'avviso 41 1.3 del giugno 2022 e sta creando confusione tra i service provider.
Grazie

**Comment by peppelinux** [comment]
Grazie @nicola-milani 

risolta qui https://github.com/italia/spid-cie-oidc-docs/releases/tag/1.1.5
