### ISSUE TITLE
Differenza tra spid-cie-oidc-docs e avviso SPID 41-2.0 circa l'uso di jwks e signed_jwks_uri per RP

### ISSUE THREAD

**Issue by rglauco** [italia/spid-cie-oidc-docs#196]
In riferimento a SPID, nel [testo relativo ai metadati per RP](https://docs.italia.it/italia/spid/spid-cie-oidc-docs/it/versione-corrente/metadata_oidc_rp.html), viene prescritto l'uso del solo **jwks**.

Invece nell'[Avviso SPID 41-2.0](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n41_v2_integrazioni_llgg._openid_connect_in_spid_f.pdf) è indicato che gli RP possono usare alternativamente **jwks** o **signed_jwks_uri**.

**Comment by peppelinux** [comment]
l'uso del solo jwks è CIE oriented

una PR che chiarifica in un box che signed_jwks_uri non è usabile nei RP CIE è pertanto richiesta

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/spid-cie-oidc-docs/releases/tag/1.2.0
