### ISSUE TITLE
jwks per federazione cie-id

### ISSUE THREAD

**Issue by ebusi** [italia/spid-cie-oidc-docs#198]
Salve, 

ho appena superato il passaggio di sottomissione del EC tramite portale CIE.
Ho avuto alcuni problemi che con l'aiuto del canale Slack sono riuscito a risolvere, in particolare il valore jwks all'interno dell'entity configuration sembra dover essere obbligatoriamente diviso in due componenti: una con `"use": "sig"` ed una con `"use": "enc"`.

Confermate questo comportamento?
In caso credo avrebbe senso documentarlo.

**Comment by peppelinux** [comment]
@ebusi questo comportamento non dovrebbe essere documentato perché la specifica e gli standard a cui questa è riferita non obbligano l'uso del parametro `use`

pertanto la issue va risolta nel sistema di collaudo e nelle implementazioni piuttosto che nelle specifiche
