### ISSUE TITLE
Illustrazioni in formato SVG

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#23]
![image](https://user-images.githubusercontent.com/1297620/175102850-4017e500-4a9f-4c95-ab4d-d9d5af4edbe0.png)

**Comment by ioggstream** [comment]
@peppelinux avete provato a integrarli tramite codice mermaid come fatto in lg-modellointeroperabilità?

**Comment by ioggstream** [comment]
@sp640919 se avete domande chiedete pure.
