### ISSUE TITLE
Trust Mark claims

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#25]
Spostare la tabella dei claims trust mark sulla sezione superiore comune sia a SPID che a CIE

**Comment by sp640919** [comment]
lasciare la differenziazione spid/cie solo per quelli specifici

**Comment by agcolella** [comment]
vanno lasciati i diversi esempi non normativi

**Comment by peppelinux** [comment]
possiamo semplicemente rimandare alla specifica oidc fed
https://bitbucket.org/openid/connect/pull-requests/213

abbiamo diversi esempi non normativi li
