### ISSUE TITLE
Aggiungere MinInterno nella definizione dell'Autorità di federazione

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#30]

**Comment by peppelinux** [comment]
Hi @fmarino-ipzs 

can you give me some pointer where this information should be updated?

**Comment by fmarino-ipzs** [comment]
In section "Acronimi". In the section above "Termini Utilizzati" we should also add CIE in the Onboarding definition.

**Comment by fmarino-ipzs** [comment]
In section "Acronimi" we have AdF and FA that maybe are redundant, unless I am missing something.

**Comment by peppelinux** [comment]
pelase go ahead with a PR, we'll merge it asap
