### ISSUE TITLE
parametro scope e claims

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#32]
Credo sia il caso di aggiungere una sezione ad hoc per l'utilizzo del parametro scope e la richiesta dei claim.

**Comment by peppelinux** [comment]
Vanno nella sezione authz request, poche parole con riferimenti chiari

**Comment by fmarino-ipzs** [comment]
Ok, se per te è ok posso provare a fare una proposta in una PR, sulla base di quanto fatto nella specifica CIE

**Comment by peppelinux** [comment]
ottimo, procedi, grazie!

**Comment by peppelinux** [comment]
https://github.com/italia/spid-cie-oidc-docs/blob/main/docs/it/parametri_scope_claims.rst
