### ISSUE TITLE
Client_id response_type e scope nell'auth request

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#33]
Nella sezione "Authorization Endpoint" si dice:
"I parametri client_id, response_type e scope **devono** essere trasmessi sia come parametri sulla chiamata HTTP sia all’interno dell’oggetto request e i loro valori devono corrispondere, in ogni caso i parametri all’interno dell’oggetto request prevalgono su quelli indicati sulla chiamata HTTP."

Penso che sia meglio togliere l'obbligo normativo o quantomeno cambiare con **DOVREBBERO**. Da OIDC Core ([sez. 6.1](https://openid.net/specs/openid-connect-core-1_0.html#RequestObject)) si dice che nel caso in cui siano presenti sia come parametri HTTP e sia nel request object quest'ultimi prevalgono sugli altri. Si dice inoltre che sono REQUIRED solo da OAuth2 e non da OIDC. Visto che l'auth request nel nostro caso, di fatto è una request OIDC e non OAuth2 penso che non si debba imporre come obbligatorio. Inoltre non sono sicuro che questo requisito sia soddisfatto da molte implementazioni, il che richiederebbe una customizzazione da parte degli RP.
@peppelinux , che ne pensi?

**Comment by peppelinux** [comment]
Si per me ok. Incrociamo con le lg spid per opportuno riscontro

**Comment by damikael** [comment]
Le LL.GG. OIDC SPID specificano "devono" (Rif. [LL.GG. OIDC SPID](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_openid_connect_in_spid.pdf) Cap. 5).
Tale specifica era stata concordata con gli IdP. Nel caso in cui si decida di modificare, deve essere emanato da AgID un Avviso per correggere/integrare il documento. 
Onde evitare disallineamenti ed incomprensioni da parte degli sviluppatori, ritengo che non si può modificare fintanto che non venga eventualmente pubblicato un Avviso da AgID a riguardo. Se per CIE vale diversamente, propongo di inserire una nota valida esclusivamente per CIE.

**Comment by peppelinux** [comment]
atteniamoci alle LG OIDC SPID per evitare specificazioni contraddittorie

**Comment by sp640919** [comment]
quindi lascio DEVONO

**Comment by peppelinux** [comment]
@fmarino-ipzs @damikael per adesso realizziamo quanto definito nelle LG SPID ma lasciamo questa issue aperta perché richiede una decisione.

@sp640919 perfavore, per questa occasione, ti chiedo di creare il box di disambiguazione. Lascia DEVONO nel testo e nel box definisci che per CIE non vi è obbligo.

Con la speranza di rimuovere un giorno questo box
