### ISSUE TITLE
OpenID Connect Federation Entity Metadata (FA)

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#36]
Ogni soggetto che partecipa alla federazione deve esporre un metadata di tipo federation_entity. Per questo motivo dovremmo mettere come obbligatorio solo il resolve endpoint. Una foglia ad esempio non ha l'endpoint di fetch o di status.

Normerei anche come devono essere fatti i metadata per altre tipologie (ad es. trust_mark_issuer, oauth_authorization_server, oauth_resource, ecc. perchè importanti per i casi d'uso delle AAs)

**Comment by peppelinux** [comment]
Abbiamo/ho indicato esattamente questo a @sp640919 
considerando i testi nella PR Work4 (attualmente attiva) in quale parte del testo riscontri questa anomalia @fmarino-ipzs ?

**Comment by peppelinux** [comment]
In tutti i metadata è presente questo requisito in termini di EC assoluta
