### ISSUE TITLE
RP Metadata

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#38]
La sezione RP Metadata va rivista:
- Eliminare jwks_uri
- aggiungere:
- userinfo_signed_response_alg
- userinfo_encrypted_response_alg
- userinfo_encrypted_response_enc

Da [specifica ](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata):
userinfo_signed_response_alg
OPTIONAL. JWS alg algorithm [[JWA]](https://openid.net/specs/openid-connect-registration-1_0.html#JWA) **REQUIRED for signing UserInfo Responses**. If this is specified, the response will be [JWT](https://openid.net/specs/openid-connect-registration-1_0.html#JWT) [JWT] serialized, and signed using JWS. **The default, if omitted, is for the UserInfo Response to return the Claims as a UTF-8 encoded JSON object using the application/json content-type.**
userinfo_encrypted_response_alg
OPTIONAL. [JWE](https://openid.net/specs/openid-connect-registration-1_0.html#JWE) [JWE] alg algorithm [[JWA]](https://openid.net/specs/openid-connect-registration-1_0.html#JWA) **REQUIRED for encrypting UserInfo Responses.** If both signing and encryption are requested, the response will be signed then encrypted, with the result being a Nested JWT, as defined in [[JWT]](https://openid.net/specs/openid-connect-registration-1_0.html#JWT). **The default, if omitted, is that no encryption is performed.**
userinfo_encrypted_response_enc
OPTIONAL. JWE enc algorithm [[JWA]](https://openid.net/specs/openid-connect-registration-1_0.html#JWA) **REQUIRED for encrypting UserInfo Responses.** If userinfo_encrypted_response_alg is specified, the default for this value is A128CBC-HS256. When userinfo_encrypted_response_enc is included, userinfo_encrypted_response_alg MUST also be provided.

**Comment by peppelinux** [comment]
@sp640919 procediamo
