### ISSUE TITLE
Inserire riferimenti ai claim

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-cie-oidc-docs#5]
## Mi aspetto

- [ ] che i claim abbiano dei riferimenti alle specifiche dove presenti

## invece

- non ce l'hanno

**Comment by sp640919** [comment]
Non ho capito il requisito. Posso avere un esempio?

**Comment by peppelinux** [comment]
@sp640919 eccolo
![image](https://user-images.githubusercontent.com/1297620/175045764-52cc04d3-ba2c-4665-af7c-20c861957748.png)

per RP trovi su oidc dynamic client registration specs e per OP su Discovery Provider specs

i restanti di oidc fed li trovi su oidc federation 1.0 specs

per una visione più generale per OAuth2 usa lo IANA Registry
https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml

**Comment by peppelinux** [comment]
Fatto in tutte le sezioni dove claims e parametri sono riferibili a standard noti
![image](https://user-images.githubusercontent.com/1297620/179824183-c35d0f5d-34d3-4168-9fb8-bb34c5d02179.png)


![Uploading image.png…]()
