### ISSUE TITLE
Federation Endpoint: RP dietro intranet e requisito sul Resolve Endpoint

### ISSUE THREAD

**Issue by SimoneAvogadro** [italia/spid-cie-oidc-docs#52]
In [federation_endpoint.rst](https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/en/federation_endpoint.rst) si indica come obbligatorio il resolve endpoint: questo rappresenta un problema per eventuali RP non esposti su internet (es Intranet etc...).
Le federazioni SAML2 ad oggi non hanno problemi a permettere l'esistenza di SP entro reti private e tecnicamente lo stesso varrebbe per RP OIDC: la richiesta di esporre tale endpoint va invece in conflitto e di fatto limiterebbe maggiormente la federazone OIDC rispetto a quella SAML.
La soluzione più immediata è portare a SHOULD il livello di obbligo per il resolve endpoint.

Più in generale è forse il caso di domandarsi se non vi siano altri vincoli che impediscono/limitano gli RP non esposti e quanto sia rilevante questa esigenza:
* per i ministeri e le grandi PA
* per il processo di onboarding dove le PA più strutturate di solito non espongono pubblicamente i propri ambienti di test/collauddo/pre: ma dove l'OP ed AA dovranno cmq essere in grado di navigare tutta la catena per validarla

**Comment by peppelinux** [comment]
il modello di trust di oidc federation impone l'esposizione dell'RP su internet mediante HTTPS

nei casi in cui questo non fosse possibile a livello implementativo SPID e CIE id consentono l'adozione di Soggetti Aggregatori Full che possono interfacciare online questi tipi di RP "protetti"

l'endpoint esposto dal SA FULL per conto dei suoi discendenti risolverebbe pertanto la richiesta all'interno delle trust chain già elaborate per questi

**Comment by SimoneAvogadro** [comment]
ok, tnx: non avevo colto questo aspetto.
Quindi in sintesi tali RP non possono registrarsi direttamente con il TA e necessitano di un SA Full che li supporti, corretto?
Sul tema degli ambienti di sviluppo/collaudo c'è qualche ipotesi di lavoro per supportare gli RP?

**Comment by peppelinux** [comment]
Se gli RP non supportano oidc federation e oidc iGov, devono usare un sa full

Non ho una visione chiara sui rilasci della AgID e di ipzs degli ambienti di collaudo e come developers Italia non voglio creare sovrapposizioni, purché i test e le loro implementazioni vengano resi pubblici

OIDF ha manifestato apertura per collaborare su una piattaforma open già in uso e che richiede la copertura dei test di iGov e Federation, è scritta in Java e potrebbe interessare ipzs.

Se volete entrarci possiamo farlo con il cappello di dev ita
