### ISSUE TITLE
Resolve Endpoint e diverso ruolo delle entità della federazione

### ISSUE THREAD

**Issue by SimoneAvogadro** [italia/spid-cie-oidc-docs#53]
Nell'ambito di un TA o una SA l'obiettivo dichiarato pare quello di fornire un servizio a terze parti (RP, OP, AA)
Per gli altri soggetti l'obiettivo del Resolve Endpoint dovrebbe invece essere quello di rendere simmetrica e trasparente la visibilità sui metadati posseduti dalle controparti nell'ambito di una conversazione: cosa particolarmente gradita ed utile per risparmiare tempo nelle fasi di troubleshoting.
Se questo è l'intento la descrizone in dei [Federation Endpoint](https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/en/federation_endpoint.rst) andrebbe probabilmente rivista:
> The resolve Entity statement endpoint MUST NOT return any information regarding a subject about which it hasn't previously collected the statements and calculated the Trust Chain. In case the TMs are no more valid at the moment of the request, they MUST NOT be included in the response.

Per alcuni motivi:
- Non è adatta nel caso di TA ed SA: che probabilmente andranno a recuperare i metadati e navigadre la catena per la prima volta proprio quando viene richiamato questo endpoint
- Se l'obiettivo è rendere disponibile un endpoint "tu chi dici che io sia" è più opportuna una descrizione che esuli da concetti di stato (legato alle implementazioni) e ponga requisiti di coerenza con la sola spec OIDC Federation

e..g. di descrizione alternativa proposta: 
> The resolve Entity statement endpoint MUST comply with  [OIDC Fed spec](https://openid.net/specs/openid-connect-federation-1_0.html#rfc.section.7.2). The endpoint MUST use the very same resolve strategy it uses internally for its own operations (e.g. the RP will expose OP's metadata as it sees them).
This implies that accordin to the Italian federation's specs:
> * the resolve endpoint MUST NOT return TMs which are not valid at the time of the request
> * the resolve endpoint MUST validate the chain for the subject

**Comment by peppelinux** [comment]
> Non è adatta nel caso di TA ed SA: che probabilmente andranno a recuperare i metadati e navigadre la catena per la prima volta proprio quando viene richiamato questo endpoint

indichiamo proprio di non farlo per evitare inneschi on demand di metadata discovery

In OIDC FED viene indicato proprio di non innescare il metadata discovery se questo endpoint non risulti in qualche maniera protetto, questo è stato di seguito definito all'interno del DRAFT 21

https://openid.bitbucket.io/connect/openid-connect-federation-1_0.html#rfc.section.12.1

**Comment by SimoneAvogadro** [comment]
Ho letto la spec e mi pare che l'espressione "... should not by default ..." risponda bene all'esigenza di TA ed SA di saper risolvere i descendant su richiesta ma di non ingolfare di inutili richieste.
Seguendo la spec il TA deciderà in autonomia se fare la risoluzione (es perchè non l'ha mai fatta nemmeno una volta) oppure se non farla (es perchè l'ha già fatta 2 minuti fa ed applica un grace period).
Il TA per suo uso interno non ha mai esigenze di effettuare delle resolve (è un soggetto passivo in tal senso) e quindi per poter fare funzionare il resolve endpoint dovrà gioco forza ogni tanto fare delle risoluzioni di oggetti ancora non risolti.
Di contro la formulazione che citavo sopra ("... MUST NOT return any information regarding a subject about which it hasn't previously collected...") vieterebbe proprio anche di fare questa prima risoluzione: in questo modo il resolve endpoint per definizione dovrebbe sempre dire che non ne sa nulla di nessuna entità.

**Comment by SimoneAvogadro** [comment]
Più in generale l'intera problematica della risoluzione, del grace period/caching/anti-hammering e della validità del dato è piuttosto sovrapponibile al caso delle trust chain dei certificati TLS.
Anche lì si sono posti lo stesso problema e vista la scala e la delicatezza (visto che proteggono praticamente tutta internet) hanno sicuramente già affrontato approfonditamente i tradeoff tra la validazione completa live delle catene e meccanismo di mitigazione per non uccidere i server delle CA

**Comment by peppelinux** [comment]
@SimoneAvogadro sentiti libero di proporre qualsiasi chiarimento all'interno del testo, lavoreremo questa issue per risolverla in una PR se riusciamo a motivarla.

Per quanto riguarda la risoluzione della problematica degli stale metadata oppure la possibilità di non innescare per niente un metadata discovery: un OP nel solo possesso della chiave pubblica del TA (entity configuration di questo) può ricevere una trust chain "precompilata" da un RP all'interno delle richieste di authz o registration, grazie a questa nuova feature:

https://openid.net/specs/openid-connect-federation-1_0.html#section-10.1.1.1-2.12

sentiti libero di esprimere i tuoi commenti qui o sul bitbucket della openid foundation, considera che questa feature è stata motivata e spinta e ben accolta nelle specifiche ufficiali ma non prevediamo di gestirla in italia prima di aver un assestamento delle attuali specifiche sulle implementazioni

**Comment by peppelinux** [comment]
Risolto da https://github.com/italia/spid-cie-oidc-docs/pull/68/commits/1dc13c66a9bd956857732819e36ea7eb0c485e05
