### ISSUE TITLE
Parametro cty nel'header della response allo userinfo endpoint 

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#54]
Obbligatorio per spid avviso 41 e non richiesto per CIE. 
TODO: creare box di disambiguazione

**Comment by peppelinux** [comment]
Nota

avviso 41 indica che cty (content type) in UserInfo Response DEVE essere valorizzato a JWT tuttavia essendo un nested jwt criptato mi chiedo se il valore non debba essere pari a JWE

riferimenti
https://www.rfc-editor.org/rfc/rfc7519.html#section-5.2
https://www.rfc-editor.org/rfc/rfc7516#section-4.1.12
https://www.rfc-editor.org/rfc/rfc7515#section-4.1.10

Le specifiche comunque lo individuano come claim opzionale e non required

**Comment by peppelinux** [comment]
Si cty valorizzato a JWE non ho evidenze chiare, chiedo a Mike Jones

**Comment by peppelinux** [comment]
From https://datatracker.ietf.org/doc/html/rfc7519#section-7.1 :

5.  If a nested signing or encryption operation will be performed,
       let the Message be the JWS or JWE, and return to Step 3, using a
       "cty" (content type) value of "JWT" in the new JOSE Header
       created in that step.

**Comment by peppelinux** [comment]
confermiamo anyway il TODO per il box di disambiguazione?

**Comment by fmarino-ipzs** [comment]
Dall'RFC 7519 effettivamente mi pare sia richiesto come obbligatorio:

   In the normal case in which nested signing or encryption operations
   are not employed, the use of this Header Parameter is NOT
   RECOMMENDED.  **In the case that nested signing or encryption is
   employed, this Header Parameter MUST be present**; in this case, the
   value MUST be "JWT", to indicate that a Nested JWT is carried in this
   JWT.

Se così è direi che non si applica nessun box di disambiguazione ma proporrei di recepirlo anche per CIE.

**Comment by peppelinux** [comment]
@fmarino-ipzs 

nelle LLGG SPID si menziona, da quello che leggo, il content type della response HTTP e non il claim cty all'interno dell'header del JWT

![immagine](https://user-images.githubusercontent.com/1297620/193552571-2db720e0-e683-48a5-938c-6cc1f9b50de2.png)

**Comment by peppelinux** [comment]
nella implementazione di spid-cie-oidc-django il jwt criptato presenta il seguente header

````
{
  "alg": "RSA-OAEP",
  "enc": "A256CBC-HS512",
  "kid": "HIvo33-Km7n03ZqKDJfWVnlFudsW28YhQZx5eaXtAKA"
}
````

il jwt firmato contenuto nel precedente, presenta il seguente header

````
{
  "alg": "RS256",
  "kid": "dB67gL7ck3TFiIAf7N6_7SHvqk0MDYMEQcoGGlkUAAw"
}
````

come conforme a https://datatracker.ietf.org/doc/html/rfc7519#page-26

**Comment by peppelinux** [comment]
Già coperto da SPID Avviso 41 
![immagine](https://user-images.githubusercontent.com/1297620/195284756-0f714b75-d7de-4c36-9c13-6ad8758c1da7.png)

**Comment by peppelinux** [comment]
Risolta da https://github.com/italia/spid-cie-oidc-docs/pull/55
