### ISSUE TITLE
Valori attributo gender

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#59]
Da specifica Core OIDC vengono definiti i valori _male_ e _female_. 
Nella tabella degli attributi utente riportiamo invece i valori M e F. 
Manteniamo la versione attuale della tabella o modifichiamo in aderenza ad OIDC Core?
@peppelinux 
@nunzionapoli 
@agcolella 
@damikael

**Comment by peppelinux** [comment]
vedo M ed F nella implementazione SAML2, qui
https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/attributi.html

e credo che questo sia avvenuto per retrocompatibilità.
Credo che un mapping da M a male e così via con F con female non rappresenti un grande effort

**Comment by peppelinux** [comment]
Io proporrei di atorrare lato OP i claim aderenti allo standard oidc core, ovvero male and female.

Dal punto di vista implementativo lato RP anche se questo supporta esclusivamente lo schema legacy, con M e F, si può facilmente adottare un approccio che si adatta ad entrambe i valori.

````
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: value = 'female'

In [2]: value
Out[2]: 'female'

In [3]: value1 = 'F'

In [4]: value[0].upper()
Out[4]: 'F'

In [5]: value1[0].upper()
Out[5]: 'F'
````

**Comment by peppelinux** [comment]
Discusso nel meeting del 23 settembre 2022 con IPZS e AgID

**Comment by fmarino-ipzs** [comment]
Inserisco in una PR quanto discusso durante il meeting

**Comment by peppelinux** [comment]
IPZS: +1 per valori gender come da standard Oidc Core
DTD: +1
AGID: +1

si conferma questa modifica per il prossimo avviso Spid.
Una PR è richiesta
