### ISSUE TITLE
Uniformare tabelle claim

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-cie-oidc-docs#6]
## Mi aspetto

- [ ] che le tabelle dei claim abbiano sempre le stesse colonne

## Invece

- hanno colonne diverse

**Comment by sp640919** [comment]
Queste sono le colonne che ho applicato a tutte le tabelle di claim per uniformarle:

   :widths: 20 20 40 20
   :header-rows: 1

   * - **Claim**
     - **Tipo**
     - **Descrizione**
     - **Obbligatorio**

**Comment by ioggstream** [comment]
@sp640919 suggerisco questo approccio:

1. definire un JSON Schema per i JWT
2. Riusare gli schemi in modo consistente
3. generare le liste a partire dai JSON Schema
4. Usare le colonne:

```
* * claim
  * tipo
  * descrizione contenente OBBLIGATORIO, RACCOMANDATO, OPZIONALE
  * Riferimento alla specifica (e.g. OIDC, RFCXXX, ...)
```

**Comment by peppelinux** [comment]
Gli schema JWT li pubblichiamo su questo repo o su un repo dedicato a tutti gli schema della infrastruttura di eID nazionale @ioggstream ?

@sp640919 questi li ottieni avviando il docker-compose di spid-cie-oidc-django alla voce Tools della pagina https://trust-anchor.org:8000/onboarding/landing

**Comment by ioggstream** [comment]
@peppelinux possiamo sviluppare sull'altro repo e quando sono confermati li mettiamo qui. Ti torna?  https://github.com/teamdigitale/spid-openapi-schemes

**Comment by peppelinux** [comment]
Ok, repo fatto, lavoreremo lì
