### ISSUE TITLE
[Attribute Authority] grant token in token response

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#62]
All'interno dei gruppi di lavoro internazionali è stato suggerito di trasportare i grant tokens all'interno della response (JSON) del token endpoint

possiamo considerare di farlo senza rimuoverli da id_token

questa modifica sarà fatta aggiungendo in token endpoint response i grant tokens, replicandoli in id_token per retrocompatibilità.

**Comment by damikael** [comment]
Bene la retrocompatibilità, altrimenti la modifica avrebbe un impatto importante, non solo a livello di specifiche, ma anche relativamente alle possibilità offerte dalle implementazioni esistenti.

**Comment by peppelinux** [comment]
Io darei priorità per adesso alla implementazione SGD come prima AA reale e ricevere da IPZS le modalità per rendere questo aspetto definitivo all'interno delle specifiche delle Attribute Authority

@fmarino-ipzs

**Comment by peppelinux** [comment]
Questa proposta è rifiutata per le seguenti ragioni:

- i grant tokens sono criptati e richiedono dei metadata di envelope per rendere noti alcuni claims necessari, quali **aud**
- esponendo la lista dei token all'interno del json di token response non abbiamo modo di firmare l'envelope al punto precedente
- i grant token hanno una stretta relazione con l'ID Token, pertanto è preferibile adottare la soluzione corrente e continuare gli sviluppi su [JWT Embedded Tokens](https://github.com/rifaat-auth0/ietf/tree/main/multi-subject-jwt)

**Comment by fmarino-ipzs** [comment]
@peppelinux concordo con la tua analisi
