### ISSUE TITLE
Registro delle chiavi pubbliche

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#63]
https://bitbucket.org/openid/connect/issues/1641/feat-federation-endoint-for-historical

**Comment by peppelinux** [comment]
si richiede come obbligatorio l'uso del claim jwks per tutte le implementazioni, RP, OP, AA e via dicendo.

Se il registro verrà implementato in questa maniera si renderanno deprecati e non utilizzabili i claim jwks_uri e signed_jwks_uri.

**Comment by peppelinux** [comment]
Questa implementazione richiede che le Trust Chain calcolate per le autenticazioni dovranno essere conservate insieme agli id token secondo le regole vigenti sulla politica di conservazione.

**Comment by peppelinux** [comment]
Si richiede una PR con la sezione dedicata a questo endpoint nella documentazione e la rimozione di signed_jwks_uri

**Comment by peppelinux** [comment]
pull request sulel specifiche federation qui
https://bitbucket.org/openid/connect/pull-requests/321

in merito alle modalità di trust dei jwks oidc core e agli adeguamenti sui sistemi di onboarding SPID e CIE id si può fare riferimento ed estendere, discutere, questo schema

https://bitbucket.org/openid/connect/issues/1641/feat-federation-endoint-for-historical#comment-64179315

**Comment by peppelinux** [comment]
Riunione del 10 Ottobre:

IPZS: ok per l'endpoint. CIE id non forzerà la sottomissione/update dei jwks di oidc core in fase di onboarding. 

DTD: ok per l'endpoint. Si chiede alla AgID di dare un feedback in questo thread e di indicare, per le finalità del sistema di onboarding, se intende forzare la sottomissione/update dei jwks di oidc core e la presenza di questi, all'interno dell' entity statement emesso dal diretto superiore, nella forma di metadata_policy.

**Comment by agcolella** [comment]
@damikael

**Comment by peppelinux** [comment]
Registro pubblicato sulle specs DRAFT 24, qui
https://openid.bitbucket.io/connect/openid-connect-federation-1_0.html#name-federation-historical-keys-

propongo una sezione snella con un puntatore alla specifica ufficiale

in questa sezione sarebeb il caso di coprire la retention policy, richiesta qui:
https://github.com/italia/spid-cie-oidc-docs/issues/92

**Comment by fmarino-ipzs** [comment]
Sono d'accordo nell'inserire una sezione apposita su questo tema, ma non farei solo un puntatore. In OIDC Fed questa feature è data come opzionale (giustamente) ma nel nostro caso sarà normata come OBBLIGATORIA. Stesso discorso sul tema dei jwks core che DEVONO stare nel metadata policy. Dobbiamo poi capire che approccio usare e su quest'ultimo tema apro una issue ad hoc.
