### ISSUE TITLE
Tipo dei claim: UTC Timestamp

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-cie-oidc-docs#7]
## Mi aspetto

- che i claim di tipo JSON number (e.g. exp, iat) sia indicato. UTC Timestamp non è un tipo. UNIX Timestamp sarebbe già più chiaro. 

## Invece

- indicano UTC Timestamp

## Note

- si veda [questo thread](https://lists.w3.org/Archives/Public/ietf-http-wg/2022AprJun/0174.html) utile ad approfondire.

**Comment by sp640919** [comment]
Sostituito UNIX Timestamp in tutti
