### ISSUE TITLE
[SPID] Avviso 41 versione 2

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-docs#72]
In questa issue elenchiamo tutte le modifiche richieste nel prossimo Avviso AgID:

- [x] Federation
  - [x] ~Trust Mark status endpoint aligned to DRAFT 23~ https://github.com/italia/spid-cie-oidc-docs/pull/68/commits/1f41b8ab8f891dd9bc8bab2eca6249eb5cefb706 (verrò riportato indietro, così come nella determina federation, nel draft 25 ... nessuna azione è richiesta) 
  - [x] federation_trust_mark_status_endpoint al posto di federation_status_endpoint https://github.com/italia/spid-cie-oidc-docs/pull/117/files/16f75101c6cdd12c56dc9ef94887c8d92b4ba1c0#r1022829396
  - [x] Metadata Discovery rinominato in Federation Entity Discovery https://github.com/italia/spid-cie-oidc-docs/pull/68/commits/6eca89fff61332d919fb96f81400bd4935293496
  - [x] #79
- [ ] Metadata OP
  - Claim aggiunti:
     - **revocation_endpoint_auth_methods_supported**
     - **code_challenge_methods_supported**
     - **scopes_supported**
     - **response_types_supported**
     - **response_modes_supported** (valori: **form_post** e **query**)
     - **grant_types_supported** (valori: **refresh_token** e **authorization_code**)
     - **request_object_signing_alg_values_supported** (default: **RS256**)
     - **claims_supported**
     - **authorization_response_iss_parameter_supported** (opzionale in SPID, obbligatorio in CIE)
     - **client_registration_types_supported** (default: automatic)
     - **request_authentication_methods_supported** (default: **request_object**)
     - **logo_uri** (già definito in determina federation)
     - **organization_name** (già definito in determina federation)
  - Claim rimossi:
    - op_name (diventa organization_name)
    - op_uri (diventa homepage_uri)
- [ ] Metadata RP
  - Claim aggiunti
     - User claim in id_token criptato https://github.com/italia/spid-cie-oidc-docs/pull/55
     - **logo_uri** (già definito in determina federation)
     - **organization_name** (già definito in determina federation)
     - **id_token_signed_response_alg**
     - **id_token_encrypted_response_alg**
     - **id_token_encrypted_response_enc**
     - **userinfo_signed_response_alg**
     - **userinfo_encrypted_response_alg**
     - **userinfo_encrypted_response_enc**
     - **token_endpoint_auth_method**
     - **client_registration_types** (default: automatic)
  - Claims rimossi:
    - client_name (diventa organization_name) 
- [ ] Authorization endpoint
  - ~[x] abilitazione scopes `profile` e `email` (https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/it/authorization_endpoint.rst#parametri-scope-e-claims)~ richiede ulteriore analisi dalla AgID
  - [ ] ...
- [ ] Token endpoint
  - ~[x] User claims in id_token criptato https://github.com/italia/spid-cie-oidc-docs/pull/55~ richiede ulteriore analisi dalla AgID
- [ ] User attributes
  - [x] Gender as defined in OIDC core specs (https://github.com/italia/spid-cie-oidc-docs/pull/74)
- [x] Trust mark status endpoint:
  - [x] HTTP Method is POST and not GET according to DRAFT 25 (https://github.com/italia/spid-cie-oidc-docs/issues/94)

**Comment by peppelinux** [comment]
Considerare anche https://www.agid.gov.it/sites/default/files/repository_files/tabella_attributi_v.1.3.pdf

**Comment by peppelinux** [comment]
Ulteriore specificha sugli algoritmi che conferma avviso 41 e abilita profili di sicurezza maggiori ove possibile, qui
https://github.com/italia/spid-cie-oidc-docs/pull/88

**Comment by peppelinux** [comment]
Correzioni proposte da Avviso 41.
Le seguenti affermazioni dovrebbero essere riviste.

**PAIRWISE IDENTIFIER**
L’OP può individuare autonomamente un valore ricollegabile al Client per il “sector_identifier_uri” in caso non sia stato
possibile usando i criteri indicati nella specifica OIDC (https://openid.net/specs/openid-connect-core-
1_0.html#PairwiseAlg.).

A: sector_identifier_uri non esiste nei metadata ne tantomeno esiste un endpoint di client registration.

**INTROSPECTION**
Se il parametro “active” è valorizzato con “false” non è necessario restituire anche gli altri parametri

A: dovrebbe tornare "active" anche se valido.

**METADATA OPENID PROVIDER**
Gli OpenID Provider (OP) devono usare “jwks_uri”.
Per il “jwks_uri” è necessario che la URL afferisca allo stesso dominio, di titolarità dell’OP, sul quale è pubblicato il
metadata.

A: rivedere sulla base di quanto definito nella determina OIDC Federation. Ad ogni modo nulla ci vieta di consentire l'uso di jwks_uri agli OP. OIDC Federation ci consente di affiancare a questo anche jwks e signed_jwks_uri a patto che le jwks siano uguali.


**METADATA CLIENT**
I Relying Party (RP) possono utilizzare sia il “jwks” che il “jwks_uri”.


**CIFRATURA E `SIGILLO`**

esteso in docs italia corrente, con alcuni algoritmi raccomandati per migliore sicurezza.

**Comment by damikael** [comment]
> PAIRWISE IDENTIFIER
> L’OP può individuare autonomamente un valore ricollegabile al Client per il “sector_identifier_uri” in caso non sia stato
> possibile usando i criteri indicati nella specifica OIDC (https://openid.net/specs/openid-connect-core-
> 1_0.html#PairwiseAlg.).
> 
> A: sector_identifier_uri non esiste nei metadata ne tantomeno esiste un endpoint di client registration.

Per il Sector Identifier, OIDC Core prevede:
"If the Client has not provided a value for sector_identifier_uri in [Dynamic Client Registration](https://openid.net/specs/openid-connect-core-1_0.html#OpenID.Registration) [OpenID.Registration], the Sector Identifier used for pairwise identifier calculation is the host component of the registered redirect_uri."
OIDC SPID non ha client registration e non ha sector_identifier_uri nel metadata RP, ma l'OP, poichè non può recuperare il valore di sector_identifier_uri, individua autonomamente il valore da utilizzare per il Pairwise come previsto da OIDC Core nel caso in cui non riesca a recuperare il valore di sector_identifier_uri.

> INTROSPECTION
> Se il parametro “active” è valorizzato con “false” non è necessario restituire anche gli altri parametri
> 
> A: dovrebbe tornare "active" anche se valido.

Disambiguato

> METADATA OPENID PROVIDER
> Gli OpenID Provider (OP) devono usare “jwks_uri”.
> Per il “jwks_uri” è necessario che la URL afferisca allo stesso dominio, di titolarità dell’OP, sul quale è pubblicato il
> metadata.
> 
> A: rivedere sulla base di quanto definito nella determina OIDC Federation. Ad ogni modo nulla ci vieta di consentire l'uso di jwks_uri agli OP. OIDC Federation ci consente di affiancare a questo anche jwks e signed_jwks_uri a patto che le jwks siano uguali.

Modificato avviso 41

> METADATA CLIENT
> I Relying Party (RP) possono utilizzare sia il “jwks” che il “jwks_uri”.

Modificato avviso 41

> CIFRATURA E SIGILLO
> 
> esteso in docs italia corrente, con alcuni algoritmi raccomandati per migliore sicurezza.

Modificato avviso 41

**Comment by damikael** [comment]
> In questa issue elenchiamo tutte le modifiche richieste nel prossimo Avviso AgID:
> 
> * [x]  Federation
>   
>   * [x]  ~Trust Mark status endpoint aligned to DRAFT 23~ [1f41b8a](https://github.com/italia/spid-cie-oidc-docs/commit/1f41b8ab8f891dd9bc8bab2eca6249eb5cefb706) (verrò riportato indietro, così come nella determina federation, nel draft 25 ... nessuna azione è richiesta)
>   * [x]  federation_trust_mark_status_endpoint al posto di federation_status_endpoint https://github.com/italia/spid-cie-oidc-docs/pull/117/files/16f75101c6cdd12c56dc9ef94887c8d92b4ba1c0#r1022829396
>   * [x]  Metadata Discovery rinominato in Federation Entity Discovery [6eca89f](https://github.com/italia/spid-cie-oidc-docs/commit/6eca89fff61332d919fb96f81400bd4935293496)
>   * [x]  [allowed_leaf_entity_types in entity statement's constraints (forces the allowed roles of the descendants) #79](https://github.com/italia/spid-cie-oidc-docs/issues/79)

Modificato regolamento

> * [ ]  Metadata OP
>   
>   * Claim aggiunti:
>     
>     * **revocation_endpoint_auth_methods_supported**
>     * **code_challenge_methods_supported**
>     * **scopes_supported**
>     * **response_types_supported**
>     * **response_modes_supported** (valori: **form_post** e **query**)
>     * **grant_types_supported** (valori: **refresh_token** e **authorization_code**)
>     * **request_object_signing_alg_values_supported** (default: **RS256**)
>     * **claims_supported**
>     * **authorization_response_iss_parameter_supported** (opzionale in SPID, obbligatorio in CIE)
>     * **client_registration_types_supported** (default: automatic)
>     * **request_authentication_methods_supported** (default: **request_object**)
>     * **logo_uri** (già definito in determina federation)
>     * **organization_name** (già definito in determina federation)
>   * Claim rimossi:
>     
>     * op_name (diventa organization_name)
>     * op_uri (diventa homepage_uri)

Modificato in parte avviso 41

> * [ ]  Metadata RP
>   
>   * Claim aggiunti
>     
>     * User claim in id_token criptato [feat: user claims in the ID Token #55](https://github.com/italia/spid-cie-oidc-docs/pull/55)

Disambiguato

>     * **logo_uri** (già definito in determina federation)
>     * **organization_name** (già definito in determina federation)
>     * **id_token_signed_response_alg**
>     * **id_token_encrypted_response_alg**
>     * **id_token_encrypted_response_enc**
>     * **userinfo_signed_response_alg**
>     * **userinfo_encrypted_response_alg**
>     * **userinfo_encrypted_response_enc**
>     * **token_endpoint_auth_method**
>     * **client_registration_types** (default: automatic)
>   * Claims rimossi:
>     
>     * client_name (diventa organization_name)

Modificato in parte avviso 41

> * [ ]  Authorization endpoint
>   
>   * [x]  abilitazione scopes `profile` e `email` (https://github.com/italia/spid-cie-oidc-docs/blob/versione-corrente/docs/it/authorization_endpoint.rst#parametri-scope-e-claims)
>   * [ ]  ...

Disambiguato

> * [ ]  Token endpoint
>   
>   * [x]  User claims in id_token criptato [feat: user claims in the ID Token #55](https://github.com/italia/spid-cie-oidc-docs/pull/55)
>   * [ ]  ...

Disambiguato

> * [ ]  User attributes
>   
>   * [x]  Gender as defined in OIDC core specs ([fix: [Core] user attribute gender as oidc ore specs #74](https://github.com/italia/spid-cie-oidc-docs/pull/74))
> * [x]  Trust mark status endpoint:
>   
>   * [x]  HTTP Method is POST and not GET according to DRAFT 25 ([Trust mark status - HTTP method #94](https://github.com/italia/spid-cie-oidc-docs/issues/94))

Modificata tabella attributi e regolamento federation
