### ISSUE TITLE
Problemi editoriali (broken link/refs)

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-cie-oidc-docs#8]
## Mi aspetto

- [ ] che gli href siano formattati senza backtick, eg -  [OIDC-FED](https://spid-cie-oidc-docs.vercel.app/configurazione_federazione.html#id20)
- [ ] che gli href riportino alle specifiche citate
- [ ] I termini inglesi siano al singolare quando usati in italiano

## Invece

-  [`[OIDC-FED]`_](https://spid-cie-oidc-docs.vercel.app/configurazione_federazione.html#id20),

**Comment by ioggstream** [comment]
@peppelinux vedi qui una serie di errori di validazione dei riferimenti https://github.com/italia/spid-cie-oidc-docs/runs/6982370549?check_suite_focus=true#step:4:46

**Comment by peppelinux** [comment]
Ho chiesto a @sp640919 di risolverli

**Comment by peppelinux** [comment]
@sp640919 perfavore rimuovi tutti i riferimenti con la quadra

**Comment by peppelinux** [comment]
Ne abbiamo di ancora

![image](https://user-images.githubusercontent.com/1297620/175099224-070d47ee-5bf9-42c4-82ee-84e50236195b.png)


attendo tua conferma

**Comment by sp640919** [comment]
fatto
