### ISSUE TITLE
Response HTTP senza indicazione del protocollo

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-cie-oidc-docs#9]
## Mi aspetto

che le response http abbiano 

```
HTTP/1.1 200 OK
...

```

## Invece

hanno

```
200 OK

...
```

**Comment by sp640919** [comment]
fatto

**Comment by peppelinux** [comment]
Quando risolviamo una issue copiamo il link del commit che l'ha risolta
https://github.com/italia/spid-cie-oidc-docs/pull/4/commits/941b1975d985b746bb1734a57ffe2de0e8c77970
