### ISSUE TITLE
Metadata Policy

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#93]
Nella versione attuale delle Regole Tecniche è riportato che nell'ES PUÒ esserci il metadata policy. 
La proposta è quella di normare come obbligatoria (MUST) la presenza del metadata policy e utilizzarlo per: 

- JWKS Core acquisiti dall'EC del discendente (come da issue #63 )

- Algoritmi di cifratura e firma (quelli riportati come MUST)

Questione da discutere: che policy applichiamo? Da quello che ho capito, ci sono due alternative https://openid.net/specs/openid-connect-federation-1_0.html#name-operators :

1. Value modifiers: questo approccio andrebbe a "sovrascrivere" il metadata dell'RP in maniera "silente" --> approccio pericoloso??

2. Value checks: in questo approccio andrebbe inviato un messaggio di errore nel caso il metadata RP non fosse compliant con la policy. Questo renderebbe l'RP consapevole e lo "costringerebbe" a cambiare. In questo caso è necessario capire che tipologia di messaggio di errore viene inviato

NOTA: Andrebbe fatto un ragionamento più generale se vale la pena utilizzare il meccanismo del metadata policy per impostare le verifiche previste in fase di onboarding e relative agli EC/metadata.

**Comment by fmarino-ipzs** [comment]
Durante il meeting del 15/11/2022 si è deciso di procedere con una PR che indirizza la questione

**Comment by peppelinux** [comment]
Value modifiers è più resiliente, perché forza il livello di sicurezza

ottenendo il metadat finale relativo a se stesso, un partecipante capisce la differenza e come adeguarsi
ottenere un errore in fase di applicazione della policy, ad oggi, non offre un messaggio esplicito e gli implementatori andrebbero di conseguenza a tentativi o a ticket

meglio offrire un risultato compresibile e ridurre le richieste di assistenza e risoluzione problematiche

**Comment by peppelinux** [comment]
Vorrei collegare questa issue con https://github.com/italia/spid-cie-oidc-docs/issues/63

così da avere un'unica PR che copre gli aspetti di registro e non ripudiabilità delle request/response
In questa PR vorrei gestire la politca della retention, qui
https://github.com/italia/spid-cie-oidc-docs/issues/92

un'unica azione di consolidamento degli aspetti di non ripudiabilità, inutile frammentarla
