### ISSUE TITLE
Revoca dei TM

### ISSUE THREAD

**Issue by fmarino-ipzs** [italia/spid-cie-oidc-docs#98]
Andrebbe normato che per validare un TM un'entità DEVE verificare la validità sullo status endpoint. Per i TM di federazione SPID/CIE, nel caso di revoca, potrebbe non essere necessario andare a validare sullo status endpoint perchè il superiore elimina direttamente lo statement (del discendente) e la chain verrebbe rotta. Per le AA, invece, questo meccanismo non è possibile quindi si DEVE necessariamente andare a interrogare lo status endpoint.

**Comment by peppelinux** [comment]
Da normare sulla parte relativa alle AA e sui manuali tecnico ed implementativi di queste.
per me può rimanre PUÒ

**Comment by fmarino-ipzs** [comment]
ok, perfetto.
